[Interface]
PrivateKey = cM/ioZD0bKc0MetTxlgqZw8PoWjM14iiKep/xgegvWo=
Address = 10.200.200.3/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = j1G1WsSi+GIX5vrdGNbfMxAW7slyATXBhSI0JdJ/wgM=
AllowedIPs = 0.0.0.0/0
Endpoint = 15.235.184.98:51820
PersistentKeepalive = 25
